### ISSUE TITLE
Editable Room Name Field

### ISSUE THREAD

**Issue by Chhupten20** [ksav77/Hotel_Booking_System#10]
![issue](https://user-images.githubusercontent.com/81357271/118009285-a8384800-b36d-11eb-8455-b8fbb130b060.png)
The room name field is editable. It should not be editable by the user.

**Comment by bipul077** [comment]
![2](https://user-images.githubusercontent.com/81355345/118084404-672d4b80-b3e0-11eb-9f73-94f40d60b425.png)
I have made changes in room field and now it cannot be edited by the user.
