### ISSUE TITLE
Room Page Description Styling

### ISSUE THREAD

**Issue by ksav77** [ksav77/Hotel_Booking_System#11]
![room page1](https://user-images.githubusercontent.com/81355371/118131517-57ccf300-b41e-11eb-9b22-8b3b2dd39ff4.jpg)
![room page 2](https://user-images.githubusercontent.com/81355371/118131522-5996b680-b41e-11eb-9b28-61014b4b46d1.jpg)
Styling of description and booking form of all room pages should be similar.

**Comment by bipul077** [comment]
Ok, I will be working on it.

**Comment by bipul077** [comment]
![8](https://user-images.githubusercontent.com/81355345/118235037-e2136680-b4b3-11eb-8160-c5a31df567bd.PNG)
![9](https://user-images.githubusercontent.com/81355345/118235042-e5a6ed80-b4b3-11eb-9f9a-d48f242d74ad.PNG)
Styling of image and booking of all room pages are made similar as you suggested
