### ISSUE TITLE
Increase the Size font in the navigation bar

### ISSUE THREAD

**Issue by ksav77** [ksav77/Hotel_Booking_System#12]
![navbar](https://user-images.githubusercontent.com/81355371/118360277-9e4d5980-b5a6-11eb-8396-08e4b2eab1fe.jpg)
Increase the size of font in the navigation bar

**Comment by chiranjivi7** [comment]
![Screenshot 2021-05-16 095431](https://user-images.githubusercontent.com/81355405/118385530-5292c280-b62f-11eb-810f-5c79527418f7.png)

I have increase the size of navibar font abd edited pages are pushed to github.

**Comment by chiranjivi7** [comment]
![Screenshot 2021-05-16 095431](https://user-images.githubusercontent.com/81355405/118385556-88d04200-b62f-11eb-884f-74bc60d7f166.png)
I have increase the size of navibar font abd edited pages are pushed to github.
