### ISSUE TITLE
Change the CSS of Book button in the form of rooms page

### ISSUE THREAD

**Issue by ksav77** [ksav77/Hotel_Booking_System#13]
![Button ](https://user-images.githubusercontent.com/81355371/118393232-c055e300-b65d-11eb-9df3-b47f80ee261c.p

**Comment by chiranjivi7** [comment]
![image](https://user-images.githubusercontent.com/81355405/118393910-40ca1300-b661-11eb-9647-7065e5ee673f.png)
Book Button css is changed and uploaded.
