### ISSUE TITLE
About us 

### ISSUE THREAD

**Issue by srijan-bhandari30** [ksav77/Hotel_Booking_System#3]
Make continue link open in new tab.

**Comment by bipul077** [comment]
![Capture](https://user-images.githubusercontent.com/81355345/114731127-35818000-9d61-11eb-86cf-e2c13ac41447.PNG)
![capture1](https://user-images.githubusercontent.com/81355345/114731148-387c7080-9d61-11eb-96a6-70916594ef62.PNG)
Error related to continue button of about us page not opening in new tab is solved
