### ISSUE TITLE
Room description field missing!

### ISSUE THREAD

**Issue by Chhupten20** [ksav77/Hotel_Booking_System#7]
Description field needs to be added in the 'Image posts' section of the admin console. Admin should be able to enter the room description on each of the rooms by using this particular section. Admin should also be able to delete or edit them as well.

**Comment by bipul077** [comment]
Okay I will be working on it.

**Comment by bipul077** [comment]
![cap11](https://user-images.githubusercontent.com/81355345/115011684-a4301c00-9ece-11eb-98a2-e16e353a150d.PNG)
Description field added as you suggested.
