### ISSUE TITLE
Admin Panel Dashboard

### ISSUE THREAD

**Issue by ksav77** [ksav77/Hotel_Booking_System#8]
Rename the title of heading which is marked  in screenshot
![1111111111](https://user-images.githubusercontent.com/81355371/118004057-d8311c80-b368-11eb-8f13-6fbfeabdf7c9.jpg)

**Comment by bipul077** [comment]
Ok I will be working on it.

**Comment by bipul077** [comment]
![5](https://user-images.githubusercontent.com/81355345/118122159-2bab7500-b412-11eb-9774-7ee048bfbe89.PNG)
I have change the title of heading as you suggested.
