### ISSUE TITLE
Add Heading in Food and Beverages Page

### ISSUE THREAD

**Issue by ksav77** [ksav77/Hotel_Booking_System#9]
![food and bev](https://user-images.githubusercontent.com/81355371/118007551-f4828880-b36b-11eb-8c11-8694959311a4.jpg)

**Comment by srijan-bhandari30** [comment]
I have added the heading on food and beve
![S10](https://user-images.githubusercontent.com/81351472/118139979-a6cb5600-b427-11eb-96e7-45e52364758c.jpg)
rage page
